### ISSUE TITLE
duplicate key

### ISSUE THREAD

**Issue by RafaelBar** [shaniqwa/MPserver#16]
happens when trying to register again with the same email.
example: 
user registered with **google** , email x
~user didn't link his facebook account~
user loges out
user click signup/login with **facebook** , email x
gets error: duplicate key. 

if the email already exists, open a lightbox with the error. 

![image](https://cloud.githubusercontent.com/assets/9607838/16190965/9512ad9c-36ea-11e6-84bf-c4d33992d41a.png)

**Comment by shaniqwa** [comment]
fixed. currently if a duplicate email is found after authentication, we redirect to home page. need to add an error msg to the user
