### ISSUE TITLE
menu wont open

### ISSUE THREAD

**Issue by RafaelBar** [shaniqwa/MPserver#18]
menu wont open.
for example, try to open settings.

**Comment by shaniqwa** [comment]
what do you mean menu wont open ? which menu ? 
I can open settings...

**Comment by RafaelBar** [comment]
Im trying to open settings and i cant because of the dropdown menu, which disappearing.

**Comment by shaniqwa** [comment]
what browser? can u put a picture ?

**Comment by RafaelBar** [comment]
fixed
